version: "2"
linters:
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - contextcheck
    - copyloopvar
    - durationcheck
    - errname
    - errorlint
    - exhaustive
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - goprintffuncname
    - gosec
    - ireturn
    - maintidx
    - makezero
    - misspell
    - mnd
    - nakedret
    - nestif
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nolintlint
    - paralleltest
    - predeclared
    - staticcheck
    - tagliatelle
    - thelper
    - tparallel
    - unconvert
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    cyclop:
      max-complexity: 30
      package-average: 10
    errcheck:
      check-blank: true
      check-type-assertions: true
    exhaustive:
      check:
        - switch
        - map
    funlen:
      lines: 100
      statements: 60
      ignore-comments: true
    gocognit:
      min-complexity: 20
    goconst:
      min-occurrences: 3
    gocyclo:
      min-complexity: 20
    gochecksumtype:
      default-signifies-exhaustive: false
    gocritic:
      settings:
        captLocal:
          paramsOnly: false
        underef:
          skipRecvDeref: false
    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true
    ireturn:
      allow:
        - anon
        - error
        - empty
        - stdlib
        - sigs.k8s.io/controller-runtime/pkg/client.Client
    lll:
      line-length: 140
    mnd:
      ignored-numbers:
        - "0"
        - "1"
        - "2"
      ignored-functions:
        - cobra.*
        - strconv.*
    nolintlint:
      require-explanation: true
      require-specific: true
    perfsprint:
      strconcat: false
    revive:
      rules:
        - name: var-naming
          arguments:
            - []
            - []
            - - skipPackageNameChecks: true
    sloglint:
      no-global: all
      context: scope
    whitespace:
      multi-if: false
      multi-func: false
    wrapcheck:
      ignore-package-globs:
        - github.com/loomhq/*
    gosec:
      excludes:
        - G101
        - G404
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: pkg/kubernetes/pod.go
      - linters:
          - errcheck
        path: pkg/kubernetes/portforward.go
      - linters:
          - errcheck
          - forcetypeassert
          - funlen
          - gocognit
          - gocyclo
          - mnd
          - nestif
          - tagliatelle
        path: pkg/kubernetes/scale.go
      - linters:
          - wrapcheck
        path: cmd/
      - linters:
          - funlen
          - gocognit
          - maintidx
          - mnd
          - wrapcheck
        path: _test.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gci
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
